name: "Dependency check"

on:
  workflow_dispatch: {}
  workflow_call: {}

permissions:
  contents: read

jobs:
  dependency-check:
    name: Dependency check
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          disable-sudo: true
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check Dependencies
        uses: actions/dependency-review-action@v3
        continue-on-error: true
        with:
          config-file: "./.github/dependency-review-config.yml"
