name: Build and test

on:
  merge_group: {}

  push:
    branches:
      - main

  pull_request: {}

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Setup Buildless
        uses: buildless/setup@v1.0.2
      - name: Setup PostgreSQL
        run: sudo postgres/setup.sh
      - name: Setup MySQL
        run: sudo mysql/setup.sh
      - name: Gradle check
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check --scan
          gradle-home-cache-cleanup: true
          gradle-home-cache-includes: |
            notifications
            jdks
      - name: "Check: Dependency Review"
        if: github.event_name == 'pull_request'
        uses: actions/dependency-review-action@v3
        continue-on-error: true
        with:
          config-file: "./.github/dependency-review-config.yml"
