name: Build and test
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Setup Buildless
        uses: buildless/setup@v1.0.2
      - name: Setup PostgreSQL
        run: sudo postgres/setup.sh
      - name: Setup MySQL
        run: sudo mysql/setup.sh
      - name: Gradle check
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check --scan
          gradle-home-cache-cleanup: true
          gradle-home-cache-includes: |
            notifications
            jdks
