name: CI

on:
  merge_group: {}
  workflow_dispatch:
    inputs:
      enableAgent:
        type: boolean
        description: "Buildless Agent"
        default: false

  push:
    branches:
      - main

  pull_request: {}

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: mysecretpassword
        ports:
          - 5432:5432
      mysql:
        image: mysql:8.0.31
        env:
          MYSQL_ROOT_PASSWORD: my-secret-pw
        ports:
          - 3306:3306

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            agent.less.build:443
            cli.less.build:443
            dl.less.build:443
            edge.pkg.st:443
            github.com:443
            global.less.build:443
            gradle.pkg.st:443
            maven.pkg.st:443
            jcenter.bintray.com:443
            local.less.build:443
            plugins-artifacts.gradle.org:443
            plugins.gradle.org:443
            repo.maven.apache.org:443
            scans-in.gradle.com:443
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Setup Buildless
        uses: buildless/setup@v1.0.2
        with:
          agent: ${{ secrets.BUILDLESS_APIKEY != '' }}
      - name: Gradle check
        uses: gradle/gradle-build-action@v2.12.0
        with:
          arguments: check --scan
          cache-read-only: false
          gradle-home-cache-cleanup: true
          gradle-home-cache-includes: |
            caches
            notifications
            jdks
            wrapper
  codeql-check:
    name: Checks
    uses: "./.github/workflows/check.codeql.yml"
    secrets:
      BUILDLESS_APIKEY: ${{ secrets.BUILDLESS_APIKEY }}

  dependency-check:
    name: Checks
    uses: "./.github/workflows/check.deps.yml"
    secrets: inherit
