name: Build and test
on: [push, pull_request]
env:
  GRADLE_CACHE_USERNAME: apikey
  GRADLE_CACHE_PUSH: true
  GRADLE_CACHE_LOCAL: false
  GRADLE_CACHE_REMOTE: true
  BUILDLESS_APIKEY: ${{ secrets.BUILDLESS_APIKEY }}
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 19
      - name: Setup PostgreSQL
        run: sudo postgres/setup.sh
      - name: Setup MySQL
        run: sudo mysql/setup.sh
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Gradle check
        run: ./gradlew check --scan

