name: CI

on:
  merge_group: {}

  push:
    branches:
      - main

  pull_request: {}

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: mysecretpassword
        ports:
          - 5432:5432
      mysql:
        image: mysql:8.0.31
        env:
          MYSQL_ROOT_PASSWORD: my-secret-pw
        ports:
          - 3306:3306

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Setup Buildless
        uses: buildless/setup@v1.0.2
      - name: Gradle check
        uses: gradle/gradle-build-action@v2.10.0
        with:
          arguments: check --scan
          cache-read-only: false
          gradle-home-cache-cleanup: true
          gradle-home-cache-includes: |
            notifications
            jdks

  codeql-check:
    name: CodeQL
    uses: "./.github/workflows/check.codeql.yml"
    secrets:
      BUILDLESS_APIKEY: ${{ secrets.BUILDLESS_APIKEY }}

  dependency-check:
    name: Dependency check
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check Dependencies
        uses: actions/dependency-review-action@v3
        continue-on-error: true
        with:
          config-file: "./.github/dependency-review-config.yml"
