name: Release to Maven Central
on:
  release:
    types: [published]
    branches:
      - main
  workflow_dispatch: {}

env:
  REPOSITORY_ID: ${{ needs.staging_repository.outputs.repository_id }}
  SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
  SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
  GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
  GPG_PRIVATE_PASSWORD: ${{ secrets.GPG_PRIVATE_PASSWORD }}

jobs:
  staging_repository:
    runs-on: ubuntu-latest
    name: Create staging repository
    outputs:
      repository_id: ${{ steps.create.outputs.repository_id }}
    steps:
      - id: create
        uses: nexus-actions/create-nexus-staging-repo@main
        with:
          username: ${{ secrets.SONATYPE_USERNAME }}
          password: ${{ secrets.SONATYPE_PASSWORD }}
          staging_profile_id: ${{ secrets.SONATYPE_PROFILE_ID }}
          description: ${{ github.repository }}/${{ github.workflow }}#${{ github.run_number }}
          base_url: https://s01.oss.sonatype.org/service/local/
  publish:
    runs-on: ubuntu-latest
    name: Publish
    needs: staging_repository
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Setup Buildless
        uses: buildless/setup@v1.0.2
        with:
          agent: ${{ secrets.BUILDLESS_APIKEY != '' }}
      - name: Gradle check
        uses: gradle/gradle-build-action@v2.11.0
        with:
          arguments: publish --scan
          dependency-graph: generate-and-submit
          gradle-home-cache-includes: |
            caches
            notifications
            jdks
            wrapper
      - name: Release Sonatype Repo
        uses: nexus-actions/release-nexus-staging-repo@main
        with:
          username: ${{ secrets.SONATYPE_USERNAME }}
          password: ${{ secrets.SONATYPE_PASSWORD }}
          staging_repository_id: ${{ needs.staging_repository.outputs.repository_id }}
          base_url: https://s01.oss.sonatype.org/service/local/
